### PR TITLE
Merge json_fdw2 fork

### PR DESCRIPTION
**Pull request by nkhorman**

### CODE REVIEW

**Comment by begriffs** [comment]
There's a merge conflict in the readme which I will manually resolve and merge from the command line.

**Comment by begriffs** [comment]
I just tried to transfer ownership but got this error:

screen shot 2016-03-03 at 9 16 23 am

It may be that another member of the Citus Github organization with higher privileges needs to make the transfer. It may also be that Github considers nkhorman/json_fdw2 as part of this repo's "network." Maybe you have to delete your fork before it will let me do the transfer.

Also, just to confirm, are you comfortable including a note in the readme mentioning the Citus' initial work on the project?

**Comment by nkhorman** [comment]
Right, I expected that it wouldn't transfer until I delete my repo. I was waiting for you to say that you were ready to transfer it before I deleted mine. I'll go ahead and do that now.

Look at the bottom of the readme.md. If that is insufficient, then I will be sure to create a more prominent citation, as you suggest.

**Comment by begriffs** [comment]
OK the message about being in the network went away, but there's still a warning about my privileges. I'll have someone else here do the transfer later today.

**Comment by begriffs** [comment]
@nkhorman you're now an admin of this repo and I think Github will allow you to transfer it to your own account.

**Comment by begriffs** [comment]
:+1:

**Comment by nkhorman** [comment]
Thank you @begriffs, for shepherding this.
And thanks to everyone else at Citus Data for the starting point and for the willingness to hand it off !

:+1:

**Pull request merged**
